
package audio;

import java.io.File; 
import java.util.logging.Level; 
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author Familia Alpizar R
 */
public class VentanPrincipal extends javax.swing.JFrame {

    
    Reproductor miReproductor = new Reproductor();     
    JFileChooser archivoSeleccionado = new JFileChooser(); 
    File archivo; 
    private boolean enReproduccion;

    /**
     * Creates new form VentanPrincipal
     */
    public VentanPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        volumen = new javax.swing.JSlider();
        vol = new javax.swing.JLabel();
        reproduciendo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        volumen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                volumenAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        volumen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumenStateChanged(evt);
            }
        });

        jMenu1.setText("Canciones");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vol))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPlay)
                                .addGap(36, 36, 36)
                                .addComponent(btnStop))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(reproduciendo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vol))
                .addGap(18, 18, 18)
                .addComponent(reproduciendo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        switch (btnPlay.getText()) { 
            case "Play": 
                if (!enReproduccion&&archivo!=null) { 
                    
                    try { 
                        miReproductor.control.play(); 
                        btnPlay.setText("Pausa"); 
                        enReproduccion = true; 
                        reproduciendo.setText("Abriendo: "+archivo.getName());
                    } catch (BasicPlayerException ex) { 
                        Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
                    } 
                } 
                 if (enReproduccion) { 
            try { 
                miReproductor.control.resume(); 
                btnPlay.setText("Pausa"); 
            } catch (BasicPlayerException ex) { 
                Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
            } 
                        } 
                break; 
            case "Pausa": 
                try { 
                    miReproductor.control.pause(); 
                } catch (BasicPlayerException ex) { 
                    Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
                } 
                btnPlay.setText("Play"); 
                break; 

        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
       try { 
            miReproductor.control.stop(); 
        } catch (BasicPlayerException ex) { 
            Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
        } 
        enReproduccion = false; 
        btnPlay.setText("Play"); 
                            
    }//GEN-LAST:event_btnStopActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archiv"
                + "o MP3", "mp3", "mp3"); 
        archivoSeleccionado.setFileFilter(filtro); 

        int seleccion = archivoSeleccionado.showOpenDialog(this); 

        if (seleccion == JFileChooser.APPROVE_OPTION) { 
            archivo = archivoSeleccionado.getSelectedFile(); 
            try { 
                miReproductor.control.open(archivo);//Le decimos al control del player que abra el archivo 
            } catch (BasicPlayerException ex) { 
                Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex); 
            } 
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void volumenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_volumenAncestorAdded
    
    }//GEN-LAST:event_volumenAncestorAdded

    private void volumenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumenStateChanged
            try { 
            miReproductor.control.setGain((double)volumen.getValue()/100);
            
        } catch (BasicPlayerException ex) {
            Logger.getLogger(VentanPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }    
            vol.setText(volumen.getValue()+"%");
    }//GEN-LAST:event_volumenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JLabel reproduciendo;
    public javax.swing.JLabel vol;
    public javax.swing.JSlider volumen;
    // End of variables declaration//GEN-END:variables

}
